/**
 * @file The inputs of the form-parsing differential test (goForm.test.ts): Content-Type values for Go 1.22's
 * mime.ParseMediaType and query strings for its url.ParseQuery, as Go strings (one char per byte; UTF-8 is written
 * as its bytes). Go's answers are recorded in `__tests__/fixtures/go-verdicts.json` ("mediaTypes", "queries") by
 * fixtures/go-recorder.go.txt. Erasable TypeScript, no imports.
 */

/** UTF-8 bytes of `s`, as a one-char-per-byte string. */
const u = (s: string): string => Buffer.from(s, "utf8").toString("latin1");

const FORM = "application/x-www-form-urlencoded";

export const MEDIA_TYPE_CASES: readonly string[] = [
  "",
  "application/octet-stream",
  FORM,
  "Application/X-WWW-Form-Urlencoded",
  "APPLICATION/X-WWW-FORM-URLENCODED",
  ` ${FORM} `,
  `\t${FORM}\t`,
  `${FORM};`,
  `${FORM}; ;`,
  `${FORM};;`,
  `${FORM}; charset=UTF-8`,
  `${FORM};charset=utf-8`,
  `${FORM};charset=utf-8;`,
  `${FORM}; charset=utf-8 ;`,
  `${FORM}; charset=utf-8; `,
  `${FORM}; charset`,
  `${FORM}; charset=`,
  `${FORM}; charset = utf-8`,
  `${FORM}; charset="utf-8"`,
  `${FORM}; charset=""`,
  `${FORM}; charset="unterminated`,
  `${FORM}; x="a\\"b"`,
  `${FORM}; x="a\\b"`,
  `${FORM}; x="a\rb"`,
  `${FORM}; x="a\nb"`,
  `${FORM}; a=1; a=1`,
  `${FORM}; a=1; a=2`,
  `${FORM}; A=1; a=2`,
  `${FORM}; a*=1; a*=2`,
  `${FORM}; a*0=x; a*0=y`,
  `${FORM}; a*0=x; a*1=y`,
  `${FORM}; =x`,
  `${FORM}; a=b c`,
  `${FORM}; a=b, text/plain`,
  `${FORM}, text/plain`,
  `${FORM} ; charset=utf-8`,
  `${FORM}/x`,
  "application /x-www-form-urlencoded",
  "application/ x-www-form-urlencoded",
  "application/x-www-form-urlencoded x",
  "application",
  "/",
  "application/",
  "/x-www-form-urlencoded",
  ";charset=utf-8",
  "application/json",
  "text/plain; charset=utf-8",
  "multipart/form-data; boundary=x",
  u(`${FORM} `),
  u(` ${FORM}`),
  u(`${FORM}\u0085`),
  u(`　${FORM} `),
  u(`${FORM}; charset=utf-8`),
  u(`${FORM}; charset=é`),
  u(`${FORM}; charset="é"`),
  u("applicatİon/x-www-form-urlencoded"),
  u("APPLICATİON/X-WWW-FORM-URLENCODED"),
  u("application/x-www-form-urlencodedK"),
  u("application/x-www-form-urlencoded".replace("x", "K")),
  `${FORM}\xff`,
  `\xff${FORM}`,
  `${FORM}; charset=\xff`,
  `${FORM}\x00`,
  `${FORM}\x0b`,
];

export const QUERY_CASES: readonly string[] = [
  "",
  "token=abc",
  "token=a&token=b",
  "token=&token=b",
  "token",
  "token=",
  "=x",
  "&&&token=x&&",
  "a=1;b=2",
  ";",
  "token=x;",
  "token=x&a=1;b=2",
  "a;=1&token=x",
  "%3B=1&token=x",
  "token=x%3By",
  "%zz",
  "%",
  "%4",
  "token=%",
  "token=%4",
  "token=%zz",
  "bad=%zz&token=x",
  "token=x&bad=%zz",
  "token=x&%=1",
  "%41=%42",
  "token=%ff%00",
  "token=%E2%82%AC",
  u("token=€"),
  "token=\xff",
  "a+b=c+d",
  "+=+",
  "k=v=w",
  "a%26b=c",
  "token=a%2Bb",
  "token=%20",
  "#token=x",
  "token=x#frag",
  "?token=x",
];
