/**
 * @file The inputs of the machine-token differential tests (goParity.test.ts): minted tokens for Go 1.22's
 * cacheEntryFrom, Clerk answers for its `json.NewDecoder(io.LimitReader(body, 64<<10)).Decode`, and proxy settings
 * for its ProxyFromEnvironment, all as the Go service (src/api/m2m.go) reads them. Go's answers are recorded in
 * `__tests__/fixtures/go-m2m-verdicts.json` by fixtures/go-m2m-recorder.go.txt. Erasable TypeScript, no imports.
 * Tokens and bodies stand for bytes, one char per byte ("latin1"; `u()` writes UTF-8 as its bytes); proxy settings
 * and URLs are text, as the environment hands it over.
 */

/** UTF-8 bytes of `s`, as a one-char-per-byte string. */
const u = (s: string): string => Buffer.from(s, "utf8").toString("latin1");
const cp = (...points: number[]): string => String.fromCodePoint(...points);

/** The clock the token cases are judged at: whole seconds, plus 400 ms, so `now.Unix()` truncates. */
export const M2M_CASES_NOW_MS = 1_790_000_000_400;
const NOW = 1_790_000_000;

const b64u = (bytes: string): string => Buffer.from(bytes, "latin1").toString("base64url");
const HEADER = b64u('{"alg":"RS256","typ":"JWT"}');
/** A token whose payload is the given JSON text (as bytes). */
const tok = (payload: string): string => `${HEADER}.${b64u(payload)}.c2ln`;
const claims = (iat: number | string, exp: number | string): string => tok(`{"iat":${String(iat)},"exp":${String(exp)}}`);

const deep = (n: number): string => `${"[".repeat(n)}${"]".repeat(n)}`;

export const TOKEN_CASES: readonly string[] = [
  claims(NOW, NOW + 86400),
  claims(NOW - 100, NOW + 86300),
  claims(NOW, NOW + 59),
  claims(NOW, NOW + 60),
  claims(NOW, NOW + 61),
  claims(NOW, NOW + 7 * 86400),
  claims(NOW, NOW + 7 * 86400 + 1),
  claims(NOW - 3600, NOW),
  claims(NOW - 3601, NOW - 1),
  claims(NOW - 3600, NOW + 1),
  claims(NOW - 100, NOW + 100),
  claims(NOW - 100, NOW + 101),
  claims(NOW - 100, NOW + 102),
  claims(NOW - 61, NOW + 61),
  claims(NOW + 0.9, NOW + 86400.9),
  claims(`${String(NOW)}.5`, `${String(NOW + 86400)}.999999`),
  claims(`${String(NOW)}e0`, `${String(NOW + 86400)}E0`),
  claims("1.79e9", "1.7900864e9"),
  claims(-5, NOW + 3600),
  claims("-0", NOW + 3600),
  claims(0, NOW + 3600),
  claims(NOW, 2 ** 53),
  claims(NOW, "9007199254740993"),
  claims(NOW, 2 ** 54),
  claims(NOW, "1e400"),
  claims("1e-400", NOW + 3600),
  claims(NOW, `"${String(NOW + 3600)}"`),
  claims(NOW, "true"),
  claims(NOW, "null"),
  claims("null", NOW + 3600),
  claims(NOW, "[1]"),
  claims(NOW, "{}"),
  tok(`{"iat":${String(NOW)}}`),
  tok(`{"exp":${String(NOW + 3600)}}`),
  tok("{}"),
  tok("null"),
  tok("[]"),
  tok('"x"'),
  tok("1"),
  tok("true"),
  tok(""),
  tok(" "),
  tok(`{"IAT":${String(NOW)},"EXP":${String(NOW + 3600)}}`),
  tok(`{"Iat":${String(NOW)},"eXp":${String(NOW + 3600)}}`),
  tok(u(`{"${cp(0x131)}at":${String(NOW)},"exp":${String(NOW + 3600)}}`)),
  tok(u(`{"${cp(0x130)}at":${String(NOW)},"exp":${String(NOW + 3600)}}`)),
  tok(`{"\\u0069at":${String(NOW)},"\\u0065xp":${String(NOW + 3600)}}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)},"EXP":${String(NOW + 7200)}}`),
  tok(`{"EXP":${String(NOW + 60)},"iat":${String(NOW)},"exp":${String(NOW + 3600)},"EXP":${String(NOW + 7200)}}`),
  tok(`{"exp":${String(NOW + 3600)},"iat":${String(NOW)},"EXP":${String(NOW + 10)}}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)},"iat":null}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)},"iat":"x"}`),
  tok(`{"iat":"x","exp":${String(NOW + 3600)},"iat":${String(NOW)}}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)},"sub":"mch","scope":"a b"}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)},"x":${deep(9999)}}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)},"x":${deep(10000)}}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)},"x":"\xff\xfe"}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)},"x":"\\ud800"}`),
  tok(`\xef\xbb\xbf{"iat":${String(NOW)},"exp":${String(NOW + 3600)}}`),
  tok(` {"iat":${String(NOW)},"exp":${String(NOW + 3600)}} \n`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}}x`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}}{}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)},}`),
  tok(`{"iat":01,"exp":${String(NOW + 3600)}}`),
  tok(`{"iat":1.,"exp":${String(NOW + 3600)}}`),
  tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}`),
  `${HEADER}.${b64u(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}}`)}=.c2ln`,
  `${HEADER}.${Buffer.from(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}}`).toString("base64")}.c2ln`,
  `${HEADER}.${b64u(`{"iat":${String(NOW)},"exp":${String(NOW + 3601)}}`).replace(/(.{8})/, "$1\r\n")}.c2ln`,
  `${HEADER}.${b64u(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}}`)} .c2ln`,
  `${HEADER}.${b64u(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}}`)}A.c2ln`,
  `${HEADER}.${b64u(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}} `)}.c2ln`,
  `${HEADER}.!!!.c2ln`,
  `${HEADER}..c2ln`,
  "..",
  "",
  "not-a-jwt",
  "aaa.bbb",
  `${tok(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}}`)}.extra`,
  `x.${b64u(`{"iat":${String(NOW)},"exp":${String(NOW + 3600)}}`)}.`,
];

const big = (n: number, fill: string): string => fill.repeat(n);

/** Clerk answer bodies (bytes). */
export const BODY_CASES: readonly string[] = [
  '{"token":"a.b.c"}',
  '{"token":"a.b.c","object":"m2m_token","expiration":1}',
  ' \r\n\t{"token":"a.b.c"}',
  '{"token":"a.b.c"} trailing garbage',
  '{"token":"a.b.c"}{"token":"d.e.f"}',
  '{"token":"a.b.c"}]',
  '{"token":"a.b.c"',
  '{"token":"a.b.c",',
  '{"token":',
  "",
  "   ",
  "null",
  " null ",
  "nul",
  "[]",
  '["a.b.c"]',
  '"a.b.c"',
  "123",
  "123abc",
  "true",
  "{}",
  '{"token":null}',
  '{"token":""}',
  '{"token":1}',
  '{"token":true}',
  '{"token":["a"]}',
  '{"token":{"x":1}}',
  '{"TOKEN":"a.b.c"}',
  '{"Token":"x.y.z","token":"a.b.c"}',
  '{"token":"a.b.c","Token":"x.y.z"}',
  '{"token":"a.b.c","token":null}',
  '{"token":"a.b.c","token":1}',
  '{"token":1,"token":"a.b.c"}',
  u(`{"to${cp(0x212a)}en":"kelvin"}`),
  u(`{"to${cp(0x212b)}en":"angstrom"}`),
  '{"\\u0074oken":"escaped.key.x"}',
  '{"token":"\\u0041\\n\\"\\\\\\/"}',
  '{"token":"\\ud800x"}',
  '{"token":"\\ud83d\\ude00"}',
  '{"token":"a\xe2\x82b"}',
  '{"token":"a\xffb\xc0\x80c\xed\xa0\x80d\xf4\x90\x80\x80e"}',
  u(`{"token":"${cp(0xe9, 0x1f600)}"}`),
  '{"token":"a\tb"}',
  '{"token":"a.b.c","x":[1,2,{"y":null}]}',
  '{"token":"a.b.c","x":{bad}}',
  '{"token":"a.b.c","x":01}',
  '{"token":"a.b.c","x":1.}',
  '{"token":"a.b.c","x":-}',
  '{"token":"a.b.c","x":1e}',
  '{"token":"a.b.c","x":tru}',
  `{"token":"a.b.c","x":${deep(9998)}}`,
  `{"token":"a.b.c","x":${deep(9999)}}`,
  '{"token":"a.b.c"' + big(70_000, " ") + "}",
  `{"token":"${big(65_536 - 13, "t")}"}`,
  `{"token":"${big(65_536 - 12, "t")}"}`,
  big(65_536 - 17, " ") + '{"token":"a.b.c"}',
  big(65_536 - 18, " ") + '{"token":"a.b.c"}',
  '{"token":"a.b.c"}' + big(70_000, "x"),
];

/** Proxy environments: each is tried against every URL below. */
export const PROXY_ENVS: readonly Record<string, string>[] = [
  {},
  { HTTPS_PROXY: "http://proxy.corp:3128", HTTP_PROXY: "http://proxy.corp:8080" },
  { https_proxy: "http://lower.corp:3128", http_proxy: "http://lower.corp:8080" },
  { HTTPS_PROXY: "http://upper.corp:3128", https_proxy: "http://lower.corp:3128" },
  { HTTPS_PROXY: "", https_proxy: "http://lower.corp:3128" },
  { HTTP_PROXY: "http://proxy.corp:8080", REQUEST_METHOD: "GET" },
  { HTTPS_PROXY: "http://proxy.corp:3128", REQUEST_METHOD: "GET" },
  { HTTPS_PROXY: "proxy.corp:3128", HTTP_PROXY: "proxy.corp" },
  { HTTPS_PROXY: "10.0.0.1:3128", HTTP_PROXY: "[::1]:3128" },
  { HTTPS_PROXY: "https://proxy.corp", HTTP_PROXY: "socks5://proxy.corp:1080" },
  { HTTPS_PROXY: "HTTP://Proxy.Corp:3128/path?q#f", HTTP_PROXY: "ftp://proxy.corp" },
  { HTTPS_PROXY: "http://user:p%40ss@proxy.corp:3128", HTTP_PROXY: "http://user@proxy.corp" },
  { HTTPS_PROXY: "http://us er@proxy.corp", HTTP_PROXY: "http://user:%zz@proxy.corp" },
  { HTTPS_PROXY: "bogus value", HTTP_PROXY: ":3128" },
  { HTTPS_PROXY: "http://proxy corp", HTTP_PROXY: "http://proxy.corp:port" },
  { HTTPS_PROXY: "proxy.corp:3128/x%zz", HTTP_PROXY: "socks5:opaque" },
  { HTTPS_PROXY: "http://", HTTP_PROXY: "//proxy.corp:1" },
  { HTTPS_PROXY: "http://proxy.corp:3128", NO_PROXY: "*" },
  { HTTPS_PROXY: "http://proxy.corp:3128", no_proxy: "*" },
  { HTTPS_PROXY: "http://proxy.corp:3128", NO_PROXY: "", no_proxy: "api.clerk.com" },
  ...[
    "api.clerk.com",
    ".clerk.com",
    "*.clerk.com",
    "clerk.com",
    "lerk.com",
    ".api.clerk.com",
    "api.clerk.com:443",
    "api.clerk.com:80",
    " API.CLERK.COM ",
    "other.example,api.clerk.com",
    "a,,b",
    ",",
    "*.",
    ".",
    ":80",
    "[::1]",
    "stub.example",
    "stub.example:8080",
    "stub.example:9090",
    "10.0.0.0/8",
    "10.1.2.3",
    "10.1.2.3:80",
    "10.1.2.3:8080",
    "01.1.2.3",
    "[2001:db8::1]:8443",
    "2001:db8::1",
    "2001:db8::/32",
    "::ffff:10.0.0.0/104",
    "::ffff:10.0.0.0/80",
    "0.0.0.0/0",
    "::/0",
    "10.0.0.0/33",
    "10.0.0.0/08",
    "fe80::1%eth0",
    `b${cp(0xfc)}cher.example`,
    "xn--bcher-kva.example",
    "host.docker.internal",
    ".docker.internal",
    "*",
    "api.clerk.com,*",
  ].map((noProxy) => ({ HTTPS_PROXY: "http://proxy.corp:3128", HTTP_PROXY: "http://proxy.corp:8080", NO_PROXY: noProxy })),
];

/** Mint URLs as CLERK_API_BASE_URL makes them (or the default). */
export const PROXY_URLS: readonly string[] = [
  "https://api.clerk.com/v1/m2m_tokens",
  "https://API.clerk.com/v1/m2m_tokens",
  "https://api.clerk.com:443/v1/m2m_tokens",
  "https://api.clerk.com:8443/v1/m2m_tokens",
  "http://stub.example:8080/v1/m2m_tokens",
  "http://stub.example/v1/m2m_tokens",
  "http://localhost:1234/v1/m2m_tokens",
  "http://LOCALHOST/v1/m2m_tokens",
  "http://127.0.0.1:9/v1/m2m_tokens",
  "http://127.1.2.3/v1/m2m_tokens",
  "http://[::1]:80/v1/m2m_tokens",
  "http://[::ffff:127.0.0.1]/v1/m2m_tokens",
  "http://10.1.2.3/v1/m2m_tokens",
  "http://10.1.2.3:8080/v1/m2m_tokens",
  "http://[2001:db8::1]:8443/v1/m2m_tokens",
  "http://[::ffff:10.1.2.3]/v1/m2m_tokens",
  `https://b${cp(0xfc)}cher.example/v1/m2m_tokens`,
  "http://host.docker.internal:5555/v1/m2m_tokens",
  "http://0.0.0.0/v1/m2m_tokens",
];
